default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - pre-commit
  - manual

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
        - id: check-byte-order-marker
        - id: check-case-conflict
        - id: check-symlinks
        - id: destroyed-symlinks
        - id: check-yaml
        - id: check-json
        - id: check-toml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: mixed-line-ending
        - id: check-merge-conflict
        - id: check-added-large-files

  - repo: https://github.com/crate-ci/typos
    rev: v1.26.0
    hooks:
      - id: typos
      - id: typos
        name: commit-msg-typos
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo +nightly fmt --
        language: system
        types: [rust]
        pass_filenames: false
        stages:
            - pre-commit
