tag-name = "v{{version}}"
tag-message = "chore: Release v{{version}}"

allow-branch = ["main"]

# Run towncrier to update CHANGELOG.md and remove news fragments
pre-release-hook = ["towncrier", "build", "--version", "{{version}}", "--yes"]

sign-commit = true
sign-tag = true
# Do not run cargo publish, we handle publishing ourselves
publish = false
