tag-message = "chore: Release v{{version}}"
tag-prefix = ""
shared-version = true

publish = false

sign-commit = true
sign-tag = true

pre-release-hook = [ "sh", "-c", "$WORKSPACE_ROOT/bin/release-script" ]
