#!/bin/sh
set -e

# TODO: implement debconf support that is maintainable without duplicating the config
#. /usr/share/debconf/confmodule

CONDUWUIT_DATABASE_PATH=/var/lib/conduwuit
CONDUWUIT_CONFIG_PATH=/etc/conduwuit

case "$1" in
  configure)
    echo ''
    echo 'Make sure you edit the example config at /etc/conduwuit/conduwuit.toml before starting!'
    echo 'To start the server, run: systemctl start conduwuit.service'
    echo ''

    ;;
esac

#DEBHELPER#
