#!/bin/sh
set -e

#. /usr/share/debconf/confmodule

CONTINUWUITY_CONFIG_PATH=/etc/continuwuity
CONTINUWUITY_DATABASE_PATH=/var/lib/continuwuity
CONTINUWUITY_DATABASE_PATH_SYMLINK=/var/lib/matrix-conduit

case $1 in
  purge)
    # Remove debconf changes from the db
    #db_purge

    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."

    #

    if [ -d "$CONTINUWUITY_CONFIG_PATH" ]; then
      if test -L "$CONTINUWUITY_CONFIG_PATH"; then
        echo "Deleting continuwuity configuration files"
        rm -v -r "$CONTINUWUITY_CONFIG_PATH"
      fi
    fi

    if [ -d "$CONTINUWUITY_DATABASE_PATH" ]; then
      if test -L "$CONTINUWUITY_DATABASE_PATH"; then
        echo "Deleting continuwuity database directory"
        rm -r "$CONTINUWUITY_DATABASE_PATH"
      fi
    fi

    ;;
esac

#DEBHELPER#
