name: Checks / Prefligit

on:
  push:

jobs:
  prefligit:
    runs-on: ubuntu-latest
    env:
      FROM_REF: ${{ github.event.pull_request.base.sha || (!github.event.forced && ( github.event.before != '0000000000000000000000000000000000000000'  && github.event.before || github.sha )) || format('{0}~', github.sha) }}
      TO_REF: ${{ github.sha }}
    steps:
    - uses: ./.forgejo/actions/prefligit
      with:
        extra_args: --from-ref ${{ env.FROM_REF }} --to-ref ${{ env.TO_REF }} --hook-stage manual
