name: Checks / Prek

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  fast-checks:
    name: Pre-commit & Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: https://github.com/astral-sh/setup-uv@v5
        with:
          enable-cache: true
          ignore-nothing-to-cache: true
          cache-dependency-glob: ''

      - name: Run prek
        run: |
          uvx prek run \
            --all-files \
            --hook-stage manual \
            --show-diff-on-failure \
            --color=always \
            -v
