name: Test

on:
  push:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Test
      if: false
      run: echo $GITHUB_SHA_SHORT
