name: reflighit
description: |
  Runs reflighit, pre-commit reimplemented in Rust.
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'

runs:
  using: composite
  steps:
  - name: Install Prefligit
    shell: bash
    run: |
      curl --proto '=https' --tlsv1.2 -LsSf https://github.com/j178/prefligit/releases/download/v0.0.10/prefligit-installer.sh | sh
  - uses: actions/cache@v3
    with:
      path: ~/.cache/prefligit
      key: prefligit-0|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: prefligit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
