[package]
name = "continuwuity_admin"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "mod.rs"
crate-type = [
	"rlib",
#	"dylib",
]

[features]
brotli_compression = [
	"continuwuity-api/brotli_compression",
	"continuwuity-core/brotli_compression",
	"continuwuity-service/brotli_compression",
]
gzip_compression = [
	"continuwuity-api/gzip_compression",
	"continuwuity-core/gzip_compression",
	"continuwuity-service/gzip_compression",
]
io_uring = [
	"continuwuity-api/io_uring",
	"continuwuity-database/io_uring",
	"continuwuity-service/io_uring",
]
jemalloc = [
	"continuwuity-api/jemalloc",
	"continuwuity-core/jemalloc",
	"continuwuity-database/jemalloc",
	"continuwuity-service/jemalloc",
]
jemalloc_conf = [
	"continuwuity-api/jemalloc_conf",
	"continuwuity-core/jemalloc_conf",
	"continuwuity-database/jemalloc_conf",
	"continuwuity-service/jemalloc_conf",
]
jemalloc_prof = [
	"continuwuity-api/jemalloc_prof",
	"continuwuity-core/jemalloc_prof",
	"continuwuity-database/jemalloc_prof",
	"continuwuity-service/jemalloc_prof",
]
jemalloc_stats = [
	"continuwuity-api/jemalloc_stats",
	"continuwuity-core/jemalloc_stats",
	"continuwuity-database/jemalloc_stats",
	"continuwuity-service/jemalloc_stats",
]
release_max_log_level = [
	"continuwuity-api/release_max_log_level",
	"continuwuity-core/release_max_log_level",
	"continuwuity-database/release_max_log_level",
	"continuwuity-service/release_max_log_level",
	"tracing/max_level_trace",
	"tracing/release_max_level_info",
	"log/max_level_trace",
	"log/release_max_level_info",
]
zstd_compression = [
	"continuwuity-api/zstd_compression",
	"continuwuity-core/zstd_compression",
	"continuwuity-database/zstd_compression",
	"continuwuity-service/zstd_compression",
]

[dependencies]
clap.workspace = true
continuwuity-api.workspace = true
continuwuity-core.workspace = true
continuwuity-database.workspace = true
continuwuity-macros.workspace = true
continuwuity-service.workspace = true
const-str.workspace = true
ctor.workspace = true
dtor.workspace = true
futures.workspace = true
lettre.workspace = true
log.workspace = true
ruma.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
resolvematrix.workspace = true

[lints]
workspace = true
