blank_issues_enabled: false
contact_links:
  - name: Get support
    url: https://matrix.to/#/#continuwuity:continuwuity.org
    about: Open a web portal to join our support room
  - name: Report a security issue
    url: https://continuwuity.org/security
    about: Report a security issue to the Continuwuity team
